version: "3"
services:
  app:
    build: .
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    depends_on:
      - mongo
    #   - mysql
    environment:
      NODE_ENV: development
      JWT_SECRET: AwesomeSecret
      BASIC_AUTH: "false"
      JWT_AUTH: "false"
      API_KEY_AUTH: "true"
      OIDC_AUTH: "false"
    ports:
      - 3000:3000
    command: npm run dev

  # Si vous souhaitez utiliser Mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: base
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb:/data/db
      - ./src/seeds/seed.js:/docker-entrypoint-initdb.d/test.js:ro

  # Si vous souhaitez utiliser Mysql
  # mysql:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  mongodb: